# Generated by Django 3.2b1 on 2021-06-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='checkout',
            field=models.DateField(),
        ),
    ]
