# Generated by Django 3.2b1 on 2021-06-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('reserve', '0004_alter_reserve_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
